databases:
  - name: chatbotdb
    plan: free
    databaseName: chatbot
    user: chatbot

services:
  - type: web
    plan: free
    name: chatbot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m uvicorn chatbot.asgi:application --host 0.0.0.0 --port 8000"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbotdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4